from fuzzywuzzy import fuzz

print('{}%'.format(fuzz.partial_ratio(
    "LÁ BEM NO ALTO DO DÉCIMO SEGUNDO ANDAR DO ANO VIVE UMA LOUCA CHAMADA ESPERANÇA E ELA PENSA QUE QUANDO TODAS AS "
    "SIRENAS TODAS AS BUZINAS TODOS OS RECO-RECOS TOCAREM ATIRA-SE DELICIOSO VOO ELA SERÁ ENCONTRADA MIRACULOSAMENTE "
    "INCÓLUME NA CALÇADA OUTRA VEZ CRIANÇA E EM TORNO DELA INDAGARÁ O POVO COMO É TEU NOME MENINAZINHA DE OLHOS "
    "VERDES E ELA LHE DIRÁ É PRECISO DIZER ISSO TUDO DE NOVO ELA IA TIRAR BEM DEVAGARINHO PARA QUE NÃO ESQUEÇA MEU "
    "NOME É ESPERANÇA", "SIRENAS CALÇADA")))

print('{}%'.format(fuzz.ratio(
    "LÁ BEM NO ALTO DO DÉCIMO SEGUNDO ANDAR DO ANO VIVE UMA LOUCA CHAMADA ESPERANÇA E ELA PENSA QUE QUANDO TODAS AS "
    "SIRENAS TODAS AS BUZINAS TODOS OS RECO-RECOS TOCAREM ATIRA-SE DELICIOSO VOO ELA SERÁ ENCONTRADA MIRACULOSAMENTE "
    "INCÓLUME NA CALÇADA OUTRA VEZ CRIANÇA E EM TORNO DELA INDAGARÁ O POVO COMO É TEU NOME MENINAZINHA DE OLHOS "
    "VERDES E ELA LHE DIRÁ É PRECISO DIZER ISSO TUDO DE NOVO ELA IA TIRAR BEM DEVAGARINHO PARA QUE NÃO ESQUEÇA MEU "
    "NOME É ESPERANÇA", "ESPERANÇA Calçada criança")))
